import "./globals.css";
import { Providers } from "./Providers";
import NavBar from "@/components/NavBar";
import Header from "@/components/Header";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "IMDB clone",
  description: "Generated by create next app",
  themeColor: "#f59e0b",
  keywords: ["NextJs 13", "IMDB clone", "TailwindCss", "React"],
  authors: [{ name: "Bright Odohofre" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning={true}>
      <body>
        <Providers>
          {/* Header */}
          <Header />

          {/* Navbar */}
          <NavBar />

          {/* SearchBox */}

          {children}
        </Providers>
      </body>
    </html>
  );
}
