import Header from "@/components/Header";
import "./globals.css";
import { Providers } from "./Providers";

export const metadata = {
  title: "IMDB clone",
  description: "Generated by create next app",
  themeColor: "#111",
  keywords: ["NextJs 13", "IMDB clone", "TailwindCss", "React"],
  authors: [{ name: "Bright Odohofre" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Providers>
          
        {/* Header */}
        <Header />

        {/* Navbar */}

        {/* SearchBox */}

        {children}
        
        </Providers>
        
      </body>
    </html>
  );
}
